apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitality-app
  labels:
    app: hospitality-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hospitality-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hospitality-app
    spec:
      containers:
      - name: hospitality-app
        image: harshhhh23/hospitality-app:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20